/*
 * This source file was generated by the Gradle 'init' task
 */
package com.srijan;

import java.util.Date;
import java.util.concurrent.atomic.AtomicInteger;

public class Expense {

    private static final AtomicInteger counter = new AtomicInteger(1000);
    private int ID;
    private Date date;
    private String description;
    private double amount;

    public Expense(String Description, double amount){
        this(new Date(), Description, amount);
    }

    public Expense(Date date, String Description, double amount){

        this.amount = amount;
        this.date = date;
        this.description = Description;
        this.ID = counter.addAndGet(1);
    }


    public Date getDate() {
        return date;
    }

    public int getID() {
        return ID;
    }

    public String getDescription() {
        return description;
    }

    public double getAmount() {
        return amount;
    }

    @Override
    public String toString(){
        return "Expense{" +
                "date='" + date + '\'' +
                ", description='" + description + '\'' +
                ", amount=" + amount + '\'' +
                '}';
    }
}
